// Generated by https://quicktype.io

export interface IEstablismnet {
    id:                   string;
    ruc:                  string;
    razonSocial:          string;
    dirMatriz:            string;
    dirEstablecimiento:   string;
    estab:                string;
    ptoEmi:               string;
    obligadoContabilidad: string;
    ambiente:             string;
    activo:               boolean;
}
