// Generated by https://quicktype.io

import { ICodigoTarifa } from "../../taxes/interfaces/tax.interface";

export interface IProduct {
  id:              number;
  codigoPrincipal: string;
  nombre:          string;
  descripcion:     string;
  urlImage:        string;
  existencia:      number;
  precioUnitario:  number;
  activo:          boolean;
  codigoTarifa:    ICodigoTarifa;
}



