// Generated by https://quicktype.io

export interface IProduct {
  id:              number;
  codigoPrincipal: string;
  nombre:          string;
  descripcion:     string;
  urlImage:        string;
  existencia:      number;
  precioUnitario:  number;
  activo:          boolean;
  codigoTarifa:    ICodigoTarifa;
}

export interface ICodigoTarifa {
  id:          number;
  codigo:      string;
  descripcion: string;
  porcentaje:  number;
  activo:      boolean;
}

